apiVersion: v2
name: go-api
description: A Helm chart for Go API application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - go
  - api
  - microservice
home: https://github.com/Sidwrite/go-deploy-test
sources:
  - https://github.com/Sidwrite/go-deploy-test
maintainers:
  - name: Sidwrite
    email: sidwrite@example.com
