apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Go
spec:
  destination:
    namespace: ''
    server: https://kubernetes.default.svc
  source:
    path: helm-chart
    repoURL: https://github.com/Sidwrite/go-deploy-test.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true