apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Sidwrite/go-deploy-test.git
    targetRevision: HEAD
    path: helm-chart
    helm:
      valueFiles:
      - values.yaml
      values: |
        image:
          repository: 211125755493.dkr.ecr.us-east-2.amazonaws.com/go-app
          tag: latest
        imagePullSecrets:
        - name: ecr-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: go-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
